// Generated by https://quicktype.io

export interface ProductResp {
    description: string;
    lastUpdated: string;
    product:     Product;
    user:        User;
    id:          number;
}

interface Product {
    id:           string;
    name:         string;
    imageURL:     string;
    quantity:     number;
    SKU:          string;
    creationDate: string;
    office:       Office;
}

interface Office {
    id:   string;
    name: string;
}

interface User {
    id:       string;
    email:    string;
    fullName: string;
    isActive: boolean;
    roles:    string[];
    office:   Office;
}
