// Generated by htts://quicktype.io

export interface existenceResp {
    existance: boolean;
    product:   Product;
}

export interface Product {
    name:     string;
    SKU:      string;
    quantity: number;
}
