// Generated by https://quicktype.io

export interface Statistic {
    products:         Product[];
    mostActiveUser:   MostActiveUser[];
    mostActiveOrders: MostActiveOrder[];
}

export interface MostActiveOrder {
    user:   string;
    orders: number;
}

export interface MostActiveUser {
    user:      string;
    movements: number;
}

interface Product {
    name:     string;
    quantity: number;
}
